const test = require('node:test');
const assert = require('node:assert/strict');
const { chatWithWechatImage, generateGreeting, generateWellbeingMessage, inferOpenApplicationIntent, inferOpenDocumentIntent, isOpenApplicationRequest, inferDocumentToolCall, inferCompoundWeatherNoteTask, inferRealityToolCall, canAutoExecuteToolCalls, formatReadOnlyToolResult, formatApplicationResult, generateApplicationReply } = require('../src/agent-service');
const { TOOL_DEFINITIONS } = require('../src/automation-service');

function settings() {
  return { api: { textBaseUrl: 'https://text.example/v1', textApiKey: 'text-key', textModel: 'text-model', visionBaseUrl: 'https://vision.example/v1', visionApiKey: 'vision-key', visionModel: 'vision-model', temperature: 0.7 }, persona: { name: '小列', relationship: '搭档', description: '友好', examples: '' }, automation: {} };
}

test('YOLO marks other, vision reads the cropped bubble, then text model answers', async () => {
  const originalFetch = global.fetch;
  const calls = [];
  global.fetch = async (url, options) => {
    const body = JSON.parse(options.body); calls.push({ url, body });
    if (url.startsWith('https://vision.example')) return { ok: true, json: async () => ({ choices: [{ message: { content: [{ type: 'output_text', text: '你好，今晚有空吗？' }] } }] }) };
    return { ok: true, json: async () => ({ choices: [{ message: { content: '当然有空，怎么啦？' } }] }) };
  };
  try {
    const result = await chatWithWechatImage(settings(), 'aGVsbG8=', { available: true, latest: { sender: 'other', confidence: 0.95, x: 10, y: 20, width: 100, height: 40, right: 110, bottom: 60 } });
    assert.equal(result.reply, '当然有空，怎么啦？'); assert.equal(calls.length, 2);
    assert.equal(calls[0].body.model, 'vision-model'); assert.equal(calls[1].body.model, 'text-model');
    assert.equal(calls[0].body.messages[1].content[1].image_url.detail, 'high');
    assert.equal(JSON.stringify(calls[1].body).includes('image_url'), false); assert.equal(result.sender, 'other'); assert.equal(result.recognizedText, '你好，今晚有空吗？');
    assert.match(calls[1].body.messages[1].content, /帮使用者回复/);
    assert.match(calls[1].body.messages[1].content, /使用者第一人称/);
    assert.match(calls[1].body.messages[1].content, /不要自称桌宠/);
  } finally { global.fetch = originalFetch; }
});

test('YOLO marks self and skips both vision and text models', async () => {
  const originalFetch = global.fetch; let calls = 0;
  global.fetch = async () => { calls += 1; throw new Error('should not call model'); };
  try {
    const result = await chatWithWechatImage(settings(), 'aGVsbG8=', { available: true, latest: { sender: 'self', confidence: 0.96, x: 10, y: 20, width: 100, height: 40, right: 110, bottom: 60 } });
    assert.equal(result.reply, ''); assert.equal(result.sender, 'self'); assert.equal(calls, 0);
  } finally { global.fetch = originalFetch; }
});

test('missing YOLO model is conservative and does not call vision', async () => {
  const originalFetch = global.fetch; let calls = 0;
  global.fetch = async () => { calls += 1; throw new Error('should not call model'); };
  try {
    const result = await chatWithWechatImage(settings(), 'aGVsbG8=', { available: false, error: 'model_not_found' });
    assert.equal(result.reply, ''); assert.equal(result.sender, 'unknown'); assert.equal(calls, 0);
  } finally { global.fetch = originalFetch; }
});

test('greeting is generated by the text model with the persona system prompt', async () => {
  const originalFetch = global.fetch;
  let request;
  global.fetch = async (_url, options) => {
    request = JSON.parse(options.body);
    return { ok: true, json: async () => ({ choices: [{ message: { content: '哎呀，博士，终于想起我了吗？' } }] }) };
  };
  try {
    const config = settings();
    config.persona.description = 'FULL_PERSONA_MARKER';
    config.persona.examples = 'FULL_EXAMPLE_MARKER';
    const greeting = await generateGreeting(config, 'bubble');
    assert.equal(greeting, '哎呀，博士，终于想起我了吗？');
    assert.equal(request.messages[0].role, 'system');
    assert.match(request.messages[0].content, /搭档/);
    assert.match(request.messages[0].content, /FULL_PERSONA_MARKER/);
    assert.match(request.messages[0].content, /FULL_EXAMPLE_MARKER/);
    assert.equal(request.messages[1].role, 'user');
    assert.equal(request.tools, undefined);
  } finally { global.fetch = originalFetch; }
});

test('missing text connection returns a persona-aware startup greeting', async () => {
  const originalFetch = global.fetch;
  global.fetch = async () => { throw new Error('fetch should not be called'); };
  try {
    const config = settings();
    config.api.textApiKey = '';
    const greeting = await generateGreeting(config, 'console');
    assert.match(greeting, /小列/);
    assert.match(greeting, /搭档/);
    assert.match(greeting, /连接/);
  } finally { global.fetch = originalFetch; }
});

test('wellbeing reminder uses the complete persona without tools or chat history', async () => {
  const originalFetch = global.fetch;
  let request;
  global.fetch = async (_url, options) => {
    request = JSON.parse(options.body);
    return { ok: true, json: async () => ({ choices: [{ message: { content: '博士，坐久了就起来走两步，顺便喝口水吧。' } }] }) };
  };
  try {
    const config = settings();
    config.persona.description = 'FULL_WELLBEING_PERSONA';
    config.persona.examples = 'FULL_WELLBEING_EXAMPLE';
    const message = await generateWellbeingMessage(config, { context: '连续使用电脑很久，适合休息' });
    assert.match(message, /喝口水/);
    assert.match(request.messages[0].content, /FULL_WELLBEING_PERSONA/);
    assert.match(request.messages[0].content, /FULL_WELLBEING_EXAMPLE/);
    assert.match(request.messages[1].content, /连续使用电脑很久/);
    assert.equal(request.tools, undefined);
  } finally { global.fetch = originalFetch; }
});

test('explicit app commands get a local tool-call fallback when a provider ignores tools', () => {
  assert.equal(inferOpenApplicationIntent('请帮我打开微信')?.function.name, 'open_application');
  assert.equal(JSON.parse(inferOpenApplicationIntent('启动计算器').function.arguments).app, 'calculator');
  assert.equal(JSON.parse(inferOpenApplicationIntent('请启动钉钉客户端').function.arguments).app, '钉钉');
  assert.equal(inferOpenApplicationIntent('为什么不能打开微信'), null);
  assert.equal(inferOpenApplicationIntent('今天天气不错'), null);
  assert.equal(isOpenApplicationRequest('帮我打开'), true);
  assert.equal(isOpenApplicationRequest('为什么不能打开微信'), false);
  assert.match(formatApplicationResult({ ok: true }, 'calculator', { persona: { name: '拉普兰德', relationship: '博士', examples: '哈哈' } }), /^博士，已经帮你打开计算器了。.*哈哈/);
  assert.match(formatApplicationResult({ ok: false, error: '没有窗口' }, 'wechat', { persona: { name: '拉普兰德', relationship: '博士', examples: '哈哈' } }), /^博士，这次没能打开微信：没有窗口.*哈哈/);
});

test('opening an application is automatic after computer-operation permission is enabled', () => {
  const appCall = [{ function: { name: 'open_application' } }];
  assert.equal(canAutoExecuteToolCalls({ automation: { enabled: true, autoExecute: false } }, appCall), true);
  assert.equal(canAutoExecuteToolCalls({ automation: { enabled: false, autoExecute: true } }, appCall), false);
  assert.equal(canAutoExecuteToolCalls({ automation: { enabled: false, autoExecute: false } }, [{ function: { name: 'get_weather' } }]), true);
  assert.equal(canAutoExecuteToolCalls({ automation: { enabled: true, autoExecute: false } }, [{ function: { name: 'send_text_to_active_wechat' } }]), false);
});

test('application confirmations are rewritten by the text model after execution', async () => {
  const originalFetch = global.fetch;
  let request;
  global.fetch = async (_url, options) => {
    request = JSON.parse(options.body);
    return { ok: true, json: async () => ({ choices: [{ message: { content: '博士，微信已经打开啦。要不要接着处理消息？' } }] }) };
  };
  try {
    const reply = await generateApplicationReply(settings(), '帮我打开微信', { ok: true }, 'wechat');
    assert.equal(reply, '博士，微信已经打开啦。要不要接着处理消息？');
    assert.equal(request.tools, undefined);
    assert.match(request.messages[1].content, /自然的中文回应/);
  } finally { global.fetch = originalFetch; }
});

test('reality questions get local read-only tool fallbacks', () => {
  assert.equal(inferRealityToolCall('现在几点')?.function.name, 'get_current_time');
  assert.equal(inferRealityToolCall('我在哪里')?.function.name, 'get_system_location');
  assert.equal(JSON.parse(inferRealityToolCall('北京天气怎么样').function.arguments).location, '北京');
  assert.equal(JSON.parse(inferRealityToolCall('明天武汉的天气咋样？').function.arguments).location, '武汉');
  assert.equal(JSON.parse(inferRealityToolCall('查询一下上海后天的天气').function.arguments).location, '上海');
  assert.deepEqual(JSON.parse(inferRealityToolCall('今天的天气').function.arguments), {});
  assert.equal(inferRealityToolCall('帮我搜索 Open-Meteo').function.name, 'search_web');
});

test('read-only results remain useful when the text provider is unavailable', () => {
  assert.match(formatReadOnlyToolResult('get_current_time', { localTime: '2026年8月21日 12:00:00', timezone: 'Asia/Shanghai' }), /2026年8月21日/);
  assert.match(formatReadOnlyToolResult('get_system_location', { city: '武汉', region: '湖北', country: '中国' }), /武汉/);
  assert.match(formatReadOnlyToolResult('get_weather', {
    location: '武汉，中国',
    current: { temperatureC: 30, weather: '晴朗' },
    forecast: [{ weather: '晴朗', min: 25, max: 34 }, { weather: '小雨', min: 24, max: 31 }],
    source: 'Open-Meteo'
  }, '明天武汉的天气咋样'), /武汉.*明天.*小雨/);
  const persona = { persona: { name: '拉普兰德', description: '轻快、带点危险感', examples: '哈哈，博士。' } };
  assert.match(formatReadOnlyToolResult('get_current_time', { localTime: '现在' }, '', persona), /^拉普兰德：.*哈哈/);
  assert.match(formatReadOnlyToolResult('read_text_document', { filePath: 'documents/a.txt', content: '文档正文' }, '', persona), /documents\/a\.txt[：:][\s\S]*文档正文/);
});

test('document tools expose read and confirmed write operations', () => {
  const names = TOOL_DEFINITIONS.map((item) => item.function.name);
  for (const name of ['read_text_document', 'open_text_document_in_notepad', 'write_text_document', 'edit_text_document', 'read_word_document', 'create_word_document', 'edit_word_document']) {
    assert.ok(names.includes(name), `missing ${name}`);
  }
  assert.equal(canAutoExecuteToolCalls({ automation: { enabled: false, autoExecute: true } }, [{ function: { name: 'read_text_document' } }]), true);
  assert.equal(canAutoExecuteToolCalls({ automation: { enabled: true, autoExecute: true } }, [{ function: { name: 'read_word_document' } }]), true);
  assert.equal(canAutoExecuteToolCalls({ automation: { enabled: true, autoExecute: false } }, [{ function: { name: 'open_text_document_in_notepad' } }]), true);
  for (const name of ['edit_text_document', 'edit_word_document']) {
    assert.equal(canAutoExecuteToolCalls({ automation: { enabled: true, autoExecute: true } }, [{ function: { name } }]), false, `${name} must require confirmation`);
  }
  assert.equal(canAutoExecuteToolCalls({ automation: { enabled: true, autoExecute: true } }, [{ function: { name: 'create_word_document' } }]), true);
  assert.equal(canAutoExecuteToolCalls({ automation: { enabled: true, autoExecute: true } }, [{ function: { name: 'write_text_document', arguments: JSON.stringify({ mode: 'create' }) } }]), true);
  assert.equal(canAutoExecuteToolCalls({ automation: { enabled: true, autoExecute: true } }, [{ function: { name: 'write_text_document', arguments: JSON.stringify({ file_path: 'documents/new-note.txt', mode: 'replace' }) } }]), true);
  assert.equal(canAutoExecuteToolCalls({ automation: { enabled: true, autoExecute: true } }, [{ function: { name: 'write_text_document', arguments: JSON.stringify({ mode: 'append' }) } }]), false);
});

test('common document requests get conservative local tool fallbacks', () => {
  assert.equal(inferDocumentToolCall('请阅读 documents/计划.txt').function.name, 'read_text_document');
  const edit = inferDocumentToolCall('把 documents/计划.txt 中的“周一”改为“周二”');
  assert.equal(edit.function.name, 'edit_text_document');
  assert.deepEqual(JSON.parse(edit.function.arguments), { file_path: 'documents/计划.txt', old_text: '周一', new_text: '周二', replace_all: true });
  const create = inferDocumentToolCall('创建 documents/会议纪要.docx，内容为：本周完成项目评审。');
  assert.equal(create.function.name, 'create_word_document');
  assert.deepEqual(JSON.parse(create.function.arguments), { file_path: 'documents/会议纪要.docx', content: '本周完成项目评审。', mode: 'create' });
  const desktopCreate = inferDocumentToolCall('新建一个记事本，内容为：桌面默认保存。');
  assert.deepEqual(JSON.parse(desktopCreate.function.arguments), { file_path: 'desktop/notepad-notes.txt', content: '桌面默认保存。', mode: 'create' });
  const bareCreate = inferDocumentToolCall('创建会议纪要.docx，内容为：桌面保存。');
  assert.equal(JSON.parse(bareCreate.function.arguments).file_path, 'desktop/会议纪要.docx');
  const articleCreate = inferDocumentToolCall('创建一个会议纪要.docx，内容为：桌面保存。');
  assert.equal(JSON.parse(articleCreate.function.arguments).file_path, 'desktop/会议纪要.docx');
});

test('compound weather-to-notepad requests are split before the model can claim success', () => {
  const request = '打开记事本，查查明后两天武汉的天气，记录在记事本里';
  const weather = inferRealityToolCall(request);
  assert.equal(weather.function.name, 'get_weather');
  assert.equal(JSON.parse(weather.function.arguments).location, '武汉');
  const task = inferCompoundWeatherNoteTask(request);
  assert.equal(task.openCall.function.name, 'open_application');
  assert.equal(task.weatherCall.function.name, 'get_weather');
  assert.equal(task.filePath, 'desktop/notepad-notes.txt');
  const natural = inferCompoundWeatherNoteTask('新建一个记事本，帮我查查明天武汉的天气，记在记事本里，完事后打开给我看');
  assert.ok(natural, '“记在记事本里” must enter the compound document workflow');
});

test('opening a just-created note gets a concrete desktop file target', () => {
  const call = inferOpenDocumentIntent('打开看看');
  assert.equal(call.function.name, 'open_text_document_in_notepad');
  assert.deepEqual(JSON.parse(call.function.arguments), { file_path: 'desktop/notepad-notes.txt' });
  const explicit = inferOpenDocumentIntent('打开 desktop/武汉明日天气.txt');
  assert.deepEqual(JSON.parse(explicit.function.arguments), { file_path: 'desktop/武汉明日天气.txt' });
});
