const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('listagent', {
  getConfig: () => ipcRenderer.invoke('config:get'),
  saveConfig: (patch) => ipcRenderer.invoke('config:save', patch),
  checkForUpdates: () => ipcRenderer.invoke('update:check'),
  installUpdate: () => ipcRenderer.invoke('update:install'),
  choosePetMedia: (state) => ipcRenderer.invoke('pet:choose-media', state),
  importPersonaText: (field) => ipcRenderer.invoke('persona:import-text', field),
  startPetDrag: () => ipcRenderer.invoke('pet:drag-start'),
  movePet: (x, y) => ipcRenderer.send('pet:drag-move', x, y),
  endPetDrag: (moved) => ipcRenderer.invoke('pet:drag-end', moved === true),
  setPetScale: (scale) => ipcRenderer.send('pet:scale', scale),
  perchPet: () => ipcRenderer.invoke('pet:perch'),
  chat: (message) => ipcRenderer.invoke('agent:chat', message),
  getChatHistory: () => ipcRenderer.invoke('agent:history'),
  recordGreeting: (greeting) => ipcRenderer.invoke('agent:record-greeting', greeting),
  generateGreeting: (surface) => ipcRenderer.invoke('agent:greeting', surface),
  decideAction: (id, approved) => ipcRenderer.invoke('agent:decide-action', id, approved),
  clearChat: () => ipcRenderer.invoke('agent:clear'),
  wechatStatus: () => ipcRenderer.invoke('wechat:status'),
  startWechatMonitor: () => ipcRenderer.invoke('wechat:monitor-start'),
  stopWechatMonitor: () => ipcRenderer.invoke('wechat:monitor-stop'),
  openWechatDebug: () => ipcRenderer.invoke('window:open-wechat-debug'),
  getWechatDebugState: () => ipcRenderer.invoke('wechat:debug-state'),
  captureWechatDebug: () => ipcRenderer.invoke('wechat:debug-capture'),
  saveWechatDebugImage: () => ipcRenderer.invoke('wechat:debug-save-image'),
  openConsole: () => ipcRenderer.invoke('window:open-console'),
  openBubbleChat: () => ipcRenderer.invoke('window:open-bubble-chat'),
  closeBubbleChat: () => ipcRenderer.invoke('window:close-bubble-chat'),
  closeConfirmation: () => ipcRenderer.invoke('window:close-confirmation'),
  closeConsole: () => ipcRenderer.invoke('window:close-console'),
  quit: () => ipcRenderer.invoke('app:quit'),
  onConfigChanged: (handler) => ipcRenderer.on('config:changed', (_event, config) => handler(config)),
  onChatHistoryChanged: (handler) => ipcRenderer.on('agent:history-changed', (_event, history) => handler(history)),
  onPetMovementState: (handler) => ipcRenderer.on('pet:movement-state', (_event, state) => handler(state)),
  onDeleteAnimation: (handler) => ipcRenderer.on('pet:delete-animation', (_event, asset) => handler(asset)),
  deleteAnimationFinished: () => ipcRenderer.send('pet:delete-animation-finished'),
  onWechatMonitorEvent: (handler) => ipcRenderer.on('wechat:monitor-event', (_event, event) => handler(event)),
  onWechatDebugEvent: (handler) => ipcRenderer.on('wechat:debug-event', (_event, event) => handler(event)),
  onActionConfirmation: (handler) => ipcRenderer.on('agent:confirmation', (_event, actions) => handler(actions))
});
